services:
  pythonapp:
    build: ./python/
    command: sh -c "sleep 10s ; python3 ./app.py"
    ports:
      - 5000:5000
    volumes:
      - ./python/:/python
    depends_on:
      - mysql

  mysql:
    build: ./mysql/
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - 3307:3306
    
